version: '3.3'

services:
  postgis:
    image: postgis/postgis:14-3.2
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: 'exit 0'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
